version: "3.9"

services:
  todo_backend:
    build: .
    container_name: todo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=*,
