name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build and run services
      run: docker-compose up -d --build

    - name: Wait for Postgres to be ready
      run: |
        until docker-compose exec db pg_isready; do
          echo "Waiting for postgres..."
          sleep 1
        done

    - name: Run Tests
      run: docker-compose exec todo_backend pytest
